### ISSUE TITLE
Harden your GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-nest1m4107#1]
Enable 2FA:
* [x] proceed at https://github.com/settings/security
* [x] I recommend using the following OTP code generator: https://play.google.com/store/apps/details?id=org.liberty.android.freeotpplus&hl=en_US

**Comment by AntonUspishnyi** [comment]
I use 1Password for secrets management and advise it everyone

**Comment by webknjaz** [comment]
Such services are incompatible with OTP considerations.

**Comment by webknjaz** [comment]
You didn't complete the task.

**Comment by AntonUspishnyi** [comment]
1Password is compatible with OTP considerations, [renew](https://support.1password.com/one-time-passwords) your information please.

**Comment by webknjaz** [comment]
**security considerations**. Ability to generate tokens isn't related to the means of security.
